[package]
name = "chatV2"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.37.0", features = ["full"] }
futures-util = "0.3.30"
tokio-tungstenite = "0.21.0"
tungstenite = "0.21.0"
